services:
  filesystem-server:
    build:
      context: ./servers/filesystem
    ports:
      - 8001:8000
  memory-server:
    build:
      context: ./servers/memory
    ports:
      - 8002:8000
  time-server:
    build:
      context: ./servers/time
    ports:
      - 8003:8000

